# last version running on ubuntu 20.04, require CUDA 12.1 
FROM nvcr.io/nvidia/pytorch:23.04-py3
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install libgl1 -y
RUN pip install --upgrade pip setuptools wheel
RUN pip install --user opencv-python
RUN pip install ultralytics -U

# clone LMI AI Solutions repository
WORKDIR /home
RUN python -m pip install --upgrade pip
RUN pip install torch torchvision torchaudio
RUN pip install --user 'git+https://github.com/facebookresearch/fvcore'
RUN git clone https://github.com/facebookresearch/detectron2 detectron2
RUN pip install --user -e detectron2 
RUN pip install tensorboard numba
RUN git clone -b FAIE-1767-v0.0.6 https://github.com/lmitechnologies/LMI_AI_Solutions.git
RUN pip install onnx-graphsurgeon onnxruntime
